### PR TITLE
Move octal numbers to decimal for webpack compatibility

### PR DESCRIPTION
**Pull request by lschumm**
Resolves issue #2

### CODE REVIEW

**Comment by jessetane** [comment]
hm, what about the new es6 way?

http://2ality.com/2015/04/numbers-math-es6.html

**Comment by jessetane** [comment]
Works for me in Chrome / Safari / FF / Edge, though not IE11

**Comment by lschumm** [comment]
Ooh, didn't know about that! Pushed the update.

**Comment by jessetane** [comment]
can you squash these commits?

**Comment by lschumm** [comment]
Done!

**Comment by jessetane** [comment]
so, I do appreciate the other changes, but this isn't quite right either - some tips:
1. never add unrelated changes to a pr (the repository link is a great idea, but it doesn't belong as part of this pr)
2. generally don't bump a version in a pr, esp for someone else's package - they may have things to add before releasing
3. testling no longer works, so updating this field is meaningless - it would be great to move to a new testing system that does work though - but again, in a separate pr!

**Comment by lschumm** [comment]
...I didn't bump the version or add a repository link. I mean I forked it to make a pull request (which you need to do)

**Comment by lschumm** [comment]
Oh, I guess that's something that was done automatically (really not sure why). I'll fix.

**Comment by jessetane** [comment]
not sure what to tell you, look at package.json file in your commit?

**Comment by lschumm** [comment]
ok for some reason now it says that's the one in your GitHub... squashing commits now

**Comment by jessetane** [comment]
ok, but again no need to add pr cleanup to the commit log, so squash this so that only the relevant changes will be added

**Comment by jessetane** [comment]
ah, beat me to it :)

**Comment by jessetane** [comment]
another tip - after forking, checkout a new branch to work on your pr on, this way you can force push over it during cleanup

**Comment by jessetane** [comment]
also, this makes the history easier to read and more faithful to reality

**Comment by jessetane** [comment]
this is a bit overkill, but generally there is some really good advice here:
http://nvie.com/posts/a-successful-git-branching-model/

**Comment by lschumm** [comment]
thanks for the advice (and the module)!

**Comment by jessetane** [comment]
please do try again!

**Pull request closed without merging**
